//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UTNEntities : DbContext
    {
        public UTNEntities()
            : base("name=UTNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PERSONAS> PERSONAS { get; set; }
        public virtual DbSet<TELEFONOS> TELEFONOS { get; set; }
    
        public virtual ObjectResult<PA_COMPRAS_Result> PA_COMPRAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_COMPRAS_Result>("PA_COMPRAS");
        }
    }
}
